// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: scrud/v1/options.proto

package scrudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionKind int32

const (
	ActionKind_ACTION_KIND_UNSPECIFIED ActionKind = 0
	ActionKind_ACTION_KIND_DESCRIBE    ActionKind = 1
	ActionKind_ACTION_KIND_LIST        ActionKind = 2
	ActionKind_ACTION_KIND_MODIFY      ActionKind = 3
	ActionKind_ACTION_KIND_REMOVE      ActionKind = 4
	ActionKind_ACTION_KIND_CREATE      ActionKind = 5
	ActionKind_ACTION_KIND_RESTORE     ActionKind = 6
	ActionKind_ACTION_KIND_CUSTOM      ActionKind = 999
)

// Enum value maps for ActionKind.
var (
	ActionKind_name = map[int32]string{
		0:   "ACTION_KIND_UNSPECIFIED",
		1:   "ACTION_KIND_DESCRIBE",
		2:   "ACTION_KIND_LIST",
		3:   "ACTION_KIND_MODIFY",
		4:   "ACTION_KIND_REMOVE",
		5:   "ACTION_KIND_CREATE",
		6:   "ACTION_KIND_RESTORE",
		999: "ACTION_KIND_CUSTOM",
	}
	ActionKind_value = map[string]int32{
		"ACTION_KIND_UNSPECIFIED": 0,
		"ACTION_KIND_DESCRIBE":    1,
		"ACTION_KIND_LIST":        2,
		"ACTION_KIND_MODIFY":      3,
		"ACTION_KIND_REMOVE":      4,
		"ACTION_KIND_CREATE":      5,
		"ACTION_KIND_RESTORE":     6,
		"ACTION_KIND_CUSTOM":      999,
	}
)

func (x ActionKind) Enum() *ActionKind {
	p := new(ActionKind)
	*p = x
	return p
}

func (x ActionKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionKind) Descriptor() protoreflect.EnumDescriptor {
	return file_scrud_v1_options_proto_enumTypes[0].Descriptor()
}

func (ActionKind) Type() protoreflect.EnumType {
	return &file_scrud_v1_options_proto_enumTypes[0]
}

func (x ActionKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type InputKind int32

const (
	InputKind_INPUT_KIND_UNSPECIFIED InputKind = 0
	InputKind_INPUT_KIND_IDS         InputKind = 1
	InputKind_INPUT_KIND_ITEMS       InputKind = 2
	InputKind_INPUT_KIND_NO_ID_ITEMS InputKind = 3
)

// Enum value maps for InputKind.
var (
	InputKind_name = map[int32]string{
		0: "INPUT_KIND_UNSPECIFIED",
		1: "INPUT_KIND_IDS",
		2: "INPUT_KIND_ITEMS",
		3: "INPUT_KIND_NO_ID_ITEMS",
	}
	InputKind_value = map[string]int32{
		"INPUT_KIND_UNSPECIFIED": 0,
		"INPUT_KIND_IDS":         1,
		"INPUT_KIND_ITEMS":       2,
		"INPUT_KIND_NO_ID_ITEMS": 3,
	}
)

func (x InputKind) Enum() *InputKind {
	p := new(InputKind)
	*p = x
	return p
}

func (x InputKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InputKind) Descriptor() protoreflect.EnumDescriptor {
	return file_scrud_v1_options_proto_enumTypes[1].Descriptor()
}

func (InputKind) Type() protoreflect.EnumType {
	return &file_scrud_v1_options_proto_enumTypes[1]
}

func (x InputKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type OutputKind int32

const (
	OutputKind_OUTPUT_KIND_UNSPECIFIED OutputKind = 0
	OutputKind_OUTPUT_KIND_IDS         OutputKind = 1
	OutputKind_OUTPUT_KIND_ITEMS       OutputKind = 2
	OutputKind_OUTPUT_KIND_EMPTY       OutputKind = 3
)

// Enum value maps for OutputKind.
var (
	OutputKind_name = map[int32]string{
		0: "OUTPUT_KIND_UNSPECIFIED",
		1: "OUTPUT_KIND_IDS",
		2: "OUTPUT_KIND_ITEMS",
		3: "OUTPUT_KIND_EMPTY",
	}
	OutputKind_value = map[string]int32{
		"OUTPUT_KIND_UNSPECIFIED": 0,
		"OUTPUT_KIND_IDS":         1,
		"OUTPUT_KIND_ITEMS":       2,
		"OUTPUT_KIND_EMPTY":       3,
	}
)

func (x OutputKind) Enum() *OutputKind {
	p := new(OutputKind)
	*p = x
	return p
}

func (x OutputKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutputKind) Descriptor() protoreflect.EnumDescriptor {
	return file_scrud_v1_options_proto_enumTypes[2].Descriptor()
}

func (OutputKind) Type() protoreflect.EnumType {
	return &file_scrud_v1_options_proto_enumTypes[2]
}

func (x OutputKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type ServiceSide int32

const (
	ServiceSide_SERVICE_SIDE_UNSPECIFIED ServiceSide = 0
	ServiceSide_SERVICE_SIDE_READ_WRITE  ServiceSide = 1
	ServiceSide_SERVICE_SIDE_READ_ONLY   ServiceSide = 2
)

// Enum value maps for ServiceSide.
var (
	ServiceSide_name = map[int32]string{
		0: "SERVICE_SIDE_UNSPECIFIED",
		1: "SERVICE_SIDE_READ_WRITE",
		2: "SERVICE_SIDE_READ_ONLY",
	}
	ServiceSide_value = map[string]int32{
		"SERVICE_SIDE_UNSPECIFIED": 0,
		"SERVICE_SIDE_READ_WRITE":  1,
		"SERVICE_SIDE_READ_ONLY":   2,
	}
)

func (x ServiceSide) Enum() *ServiceSide {
	p := new(ServiceSide)
	*p = x
	return p
}

func (x ServiceSide) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceSide) Descriptor() protoreflect.EnumDescriptor {
	return file_scrud_v1_options_proto_enumTypes[3].Descriptor()
}

func (ServiceSide) Type() protoreflect.EnumType {
	return &file_scrud_v1_options_proto_enumTypes[3]
}

func (x ServiceSide) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type MethodOptions struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entity      *string                `protobuf:"bytes,1,opt,name=entity"`
	xxx_hidden_Action      ActionKind             `protobuf:"varint,2,opt,name=action,enum=scrud.v1.ActionKind"`
	xxx_hidden_Input       InputKind              `protobuf:"varint,3,opt,name=input,enum=scrud.v1.InputKind"`
	xxx_hidden_Output      OutputKind             `protobuf:"varint,4,opt,name=output,enum=scrud.v1.OutputKind"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	mi := &file_scrud_v1_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_scrud_v1_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MethodOptions) GetEntity() string {
	if x != nil {
		if x.xxx_hidden_Entity != nil {
			return *x.xxx_hidden_Entity
		}
		return ""
	}
	return ""
}

func (x *MethodOptions) GetAction() ActionKind {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Action
		}
	}
	return ActionKind_ACTION_KIND_UNSPECIFIED
}

func (x *MethodOptions) GetInput() InputKind {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			return x.xxx_hidden_Input
		}
	}
	return InputKind_INPUT_KIND_UNSPECIFIED
}

func (x *MethodOptions) GetOutput() OutputKind {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_Output
		}
	}
	return OutputKind_OUTPUT_KIND_UNSPECIFIED
}

func (x *MethodOptions) SetEntity(v string) {
	x.xxx_hidden_Entity = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *MethodOptions) SetAction(v ActionKind) {
	x.xxx_hidden_Action = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *MethodOptions) SetInput(v InputKind) {
	x.xxx_hidden_Input = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *MethodOptions) SetOutput(v OutputKind) {
	x.xxx_hidden_Output = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *MethodOptions) HasEntity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MethodOptions) HasAction() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MethodOptions) HasInput() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *MethodOptions) HasOutput() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *MethodOptions) ClearEntity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Entity = nil
}

func (x *MethodOptions) ClearAction() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Action = ActionKind_ACTION_KIND_UNSPECIFIED
}

func (x *MethodOptions) ClearInput() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Input = InputKind_INPUT_KIND_UNSPECIFIED
}

func (x *MethodOptions) ClearOutput() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Output = OutputKind_OUTPUT_KIND_UNSPECIFIED
}

type MethodOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Entity *string
	Action *ActionKind
	Input  *InputKind
	Output *OutputKind
}

func (b0 MethodOptions_builder) Build() *MethodOptions {
	m0 := &MethodOptions{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Entity != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Entity = b.Entity
	}
	if b.Action != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Action = *b.Action
	}
	if b.Input != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Input = *b.Input
	}
	if b.Output != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Output = *b.Output
	}
	return m0
}

type ServiceOptions struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Side        ServiceSide            `protobuf:"varint,1,opt,name=side,enum=scrud.v1.ServiceSide"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ServiceOptions) Reset() {
	*x = ServiceOptions{}
	mi := &file_scrud_v1_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOptions) ProtoMessage() {}

func (x *ServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_scrud_v1_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ServiceOptions) GetSide() ServiceSide {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Side
		}
	}
	return ServiceSide_SERVICE_SIDE_UNSPECIFIED
}

func (x *ServiceOptions) SetSide(v ServiceSide) {
	x.xxx_hidden_Side = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ServiceOptions) HasSide() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ServiceOptions) ClearSide() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Side = ServiceSide_SERVICE_SIDE_UNSPECIFIED
}

type ServiceOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Side *ServiceSide
}

func (b0 ServiceOptions_builder) Build() *ServiceOptions {
	m0 := &ServiceOptions{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Side != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Side = *b.Side
	}
	return m0
}

var file_scrud_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         1098,
		Name:          "scrud.v1.method",
		Tag:           "bytes,1098,opt,name=method",
		Filename:      "scrud/v1/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceOptions)(nil),
		Field:         1099,
		Name:          "scrud.v1.service",
		Tag:           "bytes,1099,opt,name=service",
		Filename:      "scrud/v1/options.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional scrud.v1.MethodOptions method = 1098;
	E_Method = &file_scrud_v1_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional scrud.v1.ServiceOptions service = 1099;
	E_Service = &file_scrud_v1_options_proto_extTypes[1]
)

var File_scrud_v1_options_proto protoreflect.FileDescriptor

const file_scrud_v1_options_proto_rawDesc = "" +
	"\n" +
	"\x16scrud/v1/options.proto\x12\bscrud.v1\x1a google/protobuf/descriptor.proto\"\xae\x01\n" +
	"\rMethodOptions\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\tR\x06entity\x12,\n" +
	"\x06action\x18\x02 \x01(\x0e2\x14.scrud.v1.ActionKindR\x06action\x12)\n" +
	"\x05input\x18\x03 \x01(\x0e2\x13.scrud.v1.InputKindR\x05input\x12,\n" +
	"\x06output\x18\x04 \x01(\x0e2\x14.scrud.v1.OutputKindR\x06output\";\n" +
	"\x0eServiceOptions\x12)\n" +
	"\x04side\x18\x01 \x01(\x0e2\x15.scrud.v1.ServiceSideR\x04side*\xd3\x01\n" +
	"\n" +
	"ActionKind\x12\x1b\n" +
	"\x17ACTION_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ACTION_KIND_DESCRIBE\x10\x01\x12\x14\n" +
	"\x10ACTION_KIND_LIST\x10\x02\x12\x16\n" +
	"\x12ACTION_KIND_MODIFY\x10\x03\x12\x16\n" +
	"\x12ACTION_KIND_REMOVE\x10\x04\x12\x16\n" +
	"\x12ACTION_KIND_CREATE\x10\x05\x12\x17\n" +
	"\x13ACTION_KIND_RESTORE\x10\x06\x12\x17\n" +
	"\x12ACTION_KIND_CUSTOM\x10\xe7\a*m\n" +
	"\tInputKind\x12\x1a\n" +
	"\x16INPUT_KIND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eINPUT_KIND_IDS\x10\x01\x12\x14\n" +
	"\x10INPUT_KIND_ITEMS\x10\x02\x12\x1a\n" +
	"\x16INPUT_KIND_NO_ID_ITEMS\x10\x03*l\n" +
	"\n" +
	"OutputKind\x12\x1b\n" +
	"\x17OUTPUT_KIND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOUTPUT_KIND_IDS\x10\x01\x12\x15\n" +
	"\x11OUTPUT_KIND_ITEMS\x10\x02\x12\x15\n" +
	"\x11OUTPUT_KIND_EMPTY\x10\x03*d\n" +
	"\vServiceSide\x12\x1c\n" +
	"\x18SERVICE_SIDE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17SERVICE_SIDE_READ_WRITE\x10\x01\x12\x1a\n" +
	"\x16SERVICE_SIDE_READ_ONLY\x10\x02:P\n" +
	"\x06method\x12\x1e.google.protobuf.MethodOptions\x18\xca\b \x01(\v2\x17.scrud.v1.MethodOptionsR\x06method:T\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18\xcb\b \x01(\v2\x18.scrud.v1.ServiceOptionsR\aserviceB\x86\x01\n" +
	"\fcom.scrud.v1B\fOptionsProtoP\x01Z'github.com/advdv/scrud/scrud/v1;scrudv1\xa2\x02\x03SXX\xaa\x02\bScrud.V1\xca\x02\bScrud\\V1\xe2\x02\x14Scrud\\V1\\GPBMetadata\xea\x02\tScrud::V1"

var file_scrud_v1_options_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_scrud_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_scrud_v1_options_proto_goTypes = []any{
	(ActionKind)(0),                     // 0: scrud.v1.ActionKind
	(InputKind)(0),                      // 1: scrud.v1.InputKind
	(OutputKind)(0),                     // 2: scrud.v1.OutputKind
	(ServiceSide)(0),                    // 3: scrud.v1.ServiceSide
	(*MethodOptions)(nil),               // 4: scrud.v1.MethodOptions
	(*ServiceOptions)(nil),              // 5: scrud.v1.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 6: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 7: google.protobuf.ServiceOptions
}
var file_scrud_v1_options_proto_depIdxs = []int32{
	0, // 0: scrud.v1.MethodOptions.action:type_name -> scrud.v1.ActionKind
	1, // 1: scrud.v1.MethodOptions.input:type_name -> scrud.v1.InputKind
	2, // 2: scrud.v1.MethodOptions.output:type_name -> scrud.v1.OutputKind
	3, // 3: scrud.v1.ServiceOptions.side:type_name -> scrud.v1.ServiceSide
	6, // 4: scrud.v1.method:extendee -> google.protobuf.MethodOptions
	7, // 5: scrud.v1.service:extendee -> google.protobuf.ServiceOptions
	4, // 6: scrud.v1.method:type_name -> scrud.v1.MethodOptions
	5, // 7: scrud.v1.service:type_name -> scrud.v1.ServiceOptions
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	6, // [6:8] is the sub-list for extension type_name
	4, // [4:6] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_scrud_v1_options_proto_init() }
func file_scrud_v1_options_proto_init() {
	if File_scrud_v1_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scrud_v1_options_proto_rawDesc), len(file_scrud_v1_options_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_scrud_v1_options_proto_goTypes,
		DependencyIndexes: file_scrud_v1_options_proto_depIdxs,
		EnumInfos:         file_scrud_v1_options_proto_enumTypes,
		MessageInfos:      file_scrud_v1_options_proto_msgTypes,
		ExtensionInfos:    file_scrud_v1_options_proto_extTypes,
	}.Build()
	File_scrud_v1_options_proto = out.File
	file_scrud_v1_options_proto_goTypes = nil
	file_scrud_v1_options_proto_depIdxs = nil
}
